#!/usr/bin/env bash
# build-bundle.sh — packs the watcher into a single bundle.cjs for one-paste
# deployment, and copies it + install.sh to public/install/ for serving.
#
#   bash infra/nicehash-watcher/build-bundle.sh
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
SRC="src"
OUT="bundle.cjs"
PUBLIC="/dev-server/public/install"

echo "==> Bundling $SRC -> $OUT"
{
  cat <<'HEADER'
"use strict";
/*
 * nicehash-watcher bundle — auto-generated by build-bundle.sh.
 * Do not edit; update src/ and re-bundle. Deploy via:
 *   curl -fsSL https://pool.honest.money/install/nicehash-watcher.sh | sudo bash
 */
HEADER
  echo "// ============================================================ src/nicehash-api.cjs"
  echo "const __nhapi_code = $(node -e "process.stdout.write(JSON.stringify(require('fs').readFileSync('src/nicehash-api.cjs','utf8')))");"
  echo "// ============================================================ src/pool-api.cjs"
  echo "const __poolapi_code = $(node -e "process.stdout.write(JSON.stringify(require('fs').readFileSync('src/pool-api.cjs','utf8')))");"
  echo "// ============================================================ src/watcher.cjs"
  echo "const __watcher_code = $(node -e "process.stdout.write(JSON.stringify(require('fs').readFileSync('src/watcher.cjs','utf8')))");"
  cat <<'LOADER'
// --- in-memory module loader for bundled sources ---
// Relative require("./nicehash-api.cjs") inside the bundled modules resolves
// to these virtual files via a Module._load hook.
const Module = require("module");
const path = require("path");
const vm = require("vm");
const __dir = path.join(__dirname || process.cwd(), "_v");
const BUNDLED = {
  "nicehash-api.cjs": __nhapi_code,
  "pool-api.cjs": __poolapi_code,
  "watcher.cjs": __watcher_code,
};
function compileVirtual(filename, source, parent) {
  const m = new Module(filename, parent);
  m.filename = filename;
  m.paths = Module._nodeModulePaths(path.dirname(filename));
  Module._cache[filename] = m;
  const wrapped = Module.wrap(source);
  const fn = vm.runInThisContext(wrapped, { filename });
  fn.call(m.exports, m.exports, (req) => Module._load(req, m, false), m, filename, path.dirname(filename));
  return m.exports;
}
const origLoad = Module._load;
Module._load = function (request, parent, isMain) {
  if (parent && typeof request === "string" && request.startsWith(".")) {
    const base = path.basename(path.normalize(path.join(path.dirname(parent.filename), request)));
    if (Object.prototype.hasOwnProperty.call(BUNDLED, base)) {
      const vfile = path.join(__dir, base);
      if (Module._cache[vfile]) return Module._cache[vfile].exports;
      return compileVirtual(vfile, BUNDLED[base], parent);
    }
  }
  return origLoad.call(this, request, parent, isMain);
};
// Run the watcher as the main module.
compileVirtual(path.join(__dir, "watcher.cjs"), __watcher_code, null);
LOADER
} > "$OUT"

echo "==> Validating bundle syntax"
node --check "$OUT"

echo "==> Smoke-testing bundle (DRY_RUN, 1s)"
DRY_RUN=true POLL_INTERVAL_SEC=1 timeout 2 node "$OUT" 2>&1 | head -8 || true

echo "==> Copying to $PUBLIC"
mkdir -p "$PUBLIC"
cp -f "$OUT" "$PUBLIC/nicehash-watcher-bundle.cjs"
cp -f install.sh "$PUBLIC/nicehash-watcher.sh"

echo "==> Done. Published at:"
echo "    https://pool.honest.money/install/nicehash-watcher.sh"
echo "    https://pool.honest.money/install/nicehash-watcher-bundle.cjs"
