import { createFileRoute } from '@tanstack/react-router'
import { createHash } from 'crypto'

// One-shot bootstrap endpoint: emits /etc/nicehash-watcher.env with the real
// credentials stored as project secrets, so they never need to be pasted into
// chat or into a public installer URL.
//
// Protected by a rotating token hash + hard expiry. Delete this route (or let
// it expire) once the watcher box has been provisioned.
const TOKEN_SHA256 =
  '51acab571c87ccbd301438e4cd331f163e10ca859621c8738f2bdb2c1600f63b'
const EXPIRES_AT = 1786618843 // unix seconds (24h from issue)

function envLine(key: string, value: string) {
  return `${key}='${value.replace(/'/g, "'\\''")}'`
}

export const Route = createFileRoute('/api/public/nicehash-env')({
  server: {
    handlers: {
      GET: async ({ request }) => {
        if (Math.floor(Date.now() / 1000) > EXPIRES_AT) {
          return new Response('Expired\n', { status: 410 })
        }

        const url = new URL(request.url)
        const token =
          url.searchParams.get('token') ??
          request.headers.get('x-bootstrap-token') ??
          ''
        const hash = createHash('sha256').update(token).digest('hex')
        if (token.length === 0 || hash !== TOKEN_SHA256) {
          return new Response('Forbidden\n', { status: 403 })
        }

        const get = (k: string) => process.env[k] ?? ''
        const missing: string[] = []
        const need = [
          'NICEHASH_API',
          'NICEHASH_SECRET',
          'NICEHASH_ORGANIZATION',
          'TELEGRAM_BOT_TOKEN',
          'TELEGRAM_CHAT_ID',
        ]
        for (const k of need) if (!get(k)) missing.push(k)
        if (missing.length) {
          return new Response(`Missing secrets: ${missing.join(', ')}\n`, {
            status: 500,
          })
        }

        const body = [
          '# Generated by pool.honest.money bootstrap endpoint',
          envLine('NICEHASH_API', get('NICEHASH_API')),
          envLine('NICEHASH_SECRET', get('NICEHASH_SECRET')),
          envLine('NICEHASH_ORGANIZATION', get('NICEHASH_ORGANIZATION')),
          envLine('TELEGRAM_BOT_TOKEN', get('TELEGRAM_BOT_TOKEN')),
          envLine('TELEGRAM_CHAT_ID', get('TELEGRAM_CHAT_ID')),
          envLine(
            'RENTAL_LTC_ADDR',
            get('RENTAL_LTC_ADDR') || 'LTyp1No4skV378NbYrR7p6d7wRzDCHgFAa',
          ),
          envLine('POOL_API_BASE', get('POOL_API_BASE') || 'https://api.stratum.pool.honest.money'),
          envLine('DRY_RUN', 'false'),
          '',
        ].join('\n')

        return new Response(body, {
          status: 200,
          headers: {
            'content-type': 'text/plain; charset=utf-8',
            'cache-control': 'no-store',
          },
        })
      },
    },
  },
})
